baseURL = 'https://thanhhoai2k4.github.io'
languageCode = 'en-us'
title = 'Deep learning'
theme = "digitalgarden"


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Portfolio'
  url = '/portfolio'
  weight = 4
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 5



[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/ThanhHoai0901'
  weight = 1
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/thanhhoai2k4'
  weight = 2
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/thanh-hoai-41b85a259/'
  weight = 3
[[menu.social]]
  name = 'Instagram'
  url = 'https://www.instagram.com/thanhhoai180104/'
  weight = 4
[[menu.social]]
  name = 'Dribbble'
  url = 'https://dribbble.com'
  weight = 5
[[menu.social]]
  name = 'Codepen'
  url = 'https://codepen.io'
  weight = 6
[[menu.social]]
  name = 'Twitch'
  url = 'https://twitch.com'
  weight = 7
[[menu.social]]
  name = 'Email'
  url = 'disbray100@gmail.com'
  weight = 8
[[menu.social]]
  name = 'RSS'
  url = '/articles/index.xml'
  weight = 9


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

